[versions]
kotlin = "2.0.0"
agp = "8.2.2"
compose-multiplatform = "1.6.10"
koin = "3.5.6"
koin-compose-mp = "1.1.5"
coroutines = "1.8.0"
ktor = "2.3.9"
sqldelight = "2.0.1"

[libraries]
# Kotlin
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

# Koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-compose-mp" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

# AndroidX
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.8.2" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
